# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: $HOME/.cache/pip
        key: pip-cache-v1
        restore-keys: |
          pip-cache-

    - name: Interpolate version in confined environment
      run: |
        python -m venv /tmp/buildenv
        source /tmp/buildenv/bin/activate
        python -m pip install --upgrade setuptools setuptools_scm nipreps-versions
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          TAG=${GITHUB_REF##*/}
        fi
        THISVERSION=$( python -m setuptools_scm )
        THISVERSION=${TAG:-$THISVERSION}
        echo "Expected VERSION: \"${THISVERSION}\""
        echo "THISVERSION=${THISVERSION}" >> $GITHUB_ENV

    - name: Build packages
      run: |
        pip install build twine
        python -m build
        twine check dist/templateflow*
        mv dist /tmp/package

    - name: Install in confined environment [pip]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/pip
      run: |
        python -m venv /tmp/pip
        source /tmp/pip/bin/activate
        pip install --upgrade pip wheel
        pip install .
        INSTALLED_VERSION=$(python -c 'import templateflow as tf; print(tf.__version__, end="")')
        echo "VERSION: \"${THISVERSION}\""
        echo "INSTALLED: \"${INSTALLED_VERSION}\""
        test "${INSTALLED_VERSION}" = "${THISVERSION}"

    - name: Install in confined environment [sdist]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/sdist
      run: |
        python -m venv /tmp/install_sdist
        source /tmp/install_sdist/bin/activate
        pip install --upgrade pip wheel
        pip install /tmp/package/templateflow*.tar.gz
        INSTALLED_VERSION=$(python -c 'import templateflow as tf; print(tf.__version__, end="")')
        echo "VERSION: \"${THISVERSION}\""
        echo "INSTALLED: \"${INSTALLED_VERSION}\""
        test "${INSTALLED_VERSION}" = "${THISVERSION}"

    - name: Re-install in confined environment [sdist]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/sdist
      run: |
        source /tmp/install_sdist/bin/activate
        pip install /tmp/package/templateflow*.tar.gz --force-reinstall
        find ${TEMPLATEFLOW_HOME} >> /tmp/.sdist-install.txt
    - name: Re-install in confined environment [sdist - missing template]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/sdist
      run: |
        rm -rf ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym
        source /tmp/install_sdist/bin/activate
        pip install /tmp/package/templateflow*.tar.gz --force-reinstall
        python -c "import templateflow; templateflow.update(overwrite=False)"
        find ${TEMPLATEFLOW_HOME} >> /tmp/.sdist-install-2.txt
        diff /tmp/.sdist-install.txt /tmp/.sdist-install-2.txt
        exit $?

    - name: Install in confined environment [wheel]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/wheel
      run: |
        python -m venv /tmp/install_wheel
        source /tmp/install_wheel/bin/activate
        pip install --upgrade pip wheel
        pip install /tmp/package/templateflow*.whl
        INSTALLED_VERSION=$(python -c 'import templateflow as tf; print(tf.__version__, end="")')
        echo "INSTALLED: \"${INSTALLED_VERSION}\""
        test "${INSTALLED_VERSION}" = "${THISVERSION}"

    - name: Re-install in confined environment [wheel]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/wheel
      run: |
        source /tmp/install_wheel/bin/activate
        pip install /tmp/package/templateflow*.whl --force-reinstall
        find ${TEMPLATEFLOW_HOME} >> /tmp/.wheel-install.txt
    - name: Re-install in confined environment [wheel - missing template]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/wheel
      run: |
        rm -rf ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym
        source /tmp/install_wheel/bin/activate
        pip install /tmp/package/templateflow*.whl --force-reinstall
        # Wheels do not run post-install hooks:
        test ! -d ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym
        python -c "import templateflow; templateflow.update(overwrite=False)"
        find ${TEMPLATEFLOW_HOME} >> /tmp/.wheel-install-2.txt
        diff /tmp/.wheel-install.txt /tmp/.wheel-install-2.txt
        exit $?

    - name: Install in confined environment [editable]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/setup_develop
      run: |
        python -m venv /tmp/setup_develop
        source /tmp/setup_develop/bin/activate
        pip install --upgrade pip wheel
        pip install -e .
        INSTALLED_VERSION=$(python -c 'import templateflow as tf; print(tf.__version__, end="")')
        echo "INSTALLED: \"${INSTALLED_VERSION}\""
        test "${INSTALLED_VERSION}" = "${THISVERSION}"

    - name: Re-install in confined environment [editable]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/setup_develop
      run: |
        source /tmp/setup_develop/bin/activate
        pip install -e .
        find ${TEMPLATEFLOW_HOME} >> /tmp/.setup-develop.txt

    - name: Re-install in confined environment [editable - missing template]
      env:
        TEMPLATEFLOW_HOME: /tmp/home/setup_develop
      run: |
        rm -rf ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym
        source /tmp/setup_develop/bin/activate
        pip install -e .
        python -c "import templateflow; templateflow.update(overwrite=False)"
        find ${TEMPLATEFLOW_HOME} >> /tmp/.setup-develop-2.txt
        diff /tmp/.setup-develop.txt /tmp/.setup-develop-2.txt
        exit $?
